approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  "@ngx-env/builder@*":
    peerDependencies:
      webpack: "*"
